# Generated by Django 4.2.16 on 2025-12-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(help_text='Unique ID from the ID column')),
                ('task_name', models.CharField(help_text='Name of the task', max_length=255)),
                ('duration_days', models.IntegerField(help_text='Duration in days')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('source_file', models.CharField(default='Project-Schedule.pdf', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(help_text='Unique identifier (e.g., Q1)', max_length=50, unique=True)),
                ('rule_summary', models.TextField(help_text='Concise summary of the rule')),
                ('measurement_basis', models.CharField(help_text='Key measurement principle', max_length=500)),
                ('source_file', models.CharField(default='URA-Circular.pdf', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
