# Generated by Django 4.2.16 on 2025-12-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_name', models.TextField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=255, unique=True)),
                ('rule_summary', models.TextField()),
                ('measurement_basis', models.TextField()),
            ],
        ),
    ]
